name: Test spacetar.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: excitedleigh/setup-nox@v2.0.0
    - name: Run tests for spacetar.
      run: make tests
    - name: Upload coverage to Coveralls.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls --service=github
